# Conexão com postgres e Relatorios do Sistema

## Instalando biblioteca de acesso com postgres e manipulação de dados e gráficos

In [1]:
!pip install --user psycopg2-binary
!pip install --user seaborn
!pip install --user pandas

Requirement already satisfied: psycopg2-binary in c:\users\luizg\appdata\roaming\python\python37\site-packages (2.7.6.1)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Requirement already satisfied: seaborn in c:\users\luizg\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: scipy>=0.14.0 in c:\users\luizg\anaconda3\lib\site-packages (from seaborn) (1.1.0)
Requirement already satisfied: numpy>=1.9.3 in c:\users\luizg\anaconda3\lib\site-packages (from seaborn) (1.15.1)
Requirement already satisfied: pandas>=0.15.2 in c:\users\luizg\anaconda3\lib\site-packages (from seaborn) (0.23.4)
Requirement already satisfied: matplotlib>=1.4.3 in c:\users\luizg\anaconda3\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\luizg\anaconda3\lib\site-packages (from pandas>=0.15.2->seaborn) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\luizg\anaconda3\lib\site-packages (from pandas>=0.15.2->seaborn) (2018.5)
Requirement already satisfied: cycler>=0.10 in c:\users\luizg\anaconda3\lib\site-packages (from matplotlib>=1.4.3->seaborn) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\luizg\anaconda3\lib\site-packages (from matplotlib>=1.4.3->seaborn) (2.2.0)
Requirement already satisfied: six>=1.10 in c:\users\luizg\anaconda3\lib\site-packages (from matplotlib>=1.4.3->seaborn) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\luizg\anaconda3\lib\site-packages (from matplotlib>=1.4.3->seaborn) (1.0.1)
Requirement already satisfied: setuptools in c:\users\luizg\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4.3->seaborn) (40.2.0)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\luizg\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\luizg\anaconda3\lib\site-packages (from pandas) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\luizg\anaconda3\lib\site-packages (from pandas) (2018.5)
Requirement already satisfied: numpy>=1.9.0 in c:\users\luizg\anaconda3\lib\site-packages (from pandas) (1.15.1)
Requirement already satisfied: six>=1.5 in c:\users\luizg\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

### Importando bibliotecas

In [2]:
import seaborn as sns
import pandas as pd
import psycopg2

### Usando psycopg2 para configurar conexão

In [3]:
conn = psycopg2.connect(host="localhost",database="S-Organizer", user="postgres", password="1234")

## Obtendo dados do database S-Organizer

# Relatório 1

### Objetivo: Buscar a agenda de 03/05/2018 de prestadores e quais solicitações estão pendentes

Código para obtenção do resultado:

In [4]:
test = pd.read_sql_query("""

select prestador.nome, servico.descricao, servico.horariomarcado, servico.valor, categoriaservico.tipo as servico_a_prestar from prestador

inner join prestador_agenda on(prestador.id_usuario = prestador_agenda.prestador_id_usuario)
inner join agenda on(agenda.id = prestador_agenda.agenda_id)

inner join agenda_solicitacao on(agenda.id = agenda_solicitacao.agenda_id)
inner join solicitacao on(agenda_solicitacao.solicitacaododia_protocolo = solicitacao.protocolo)

inner join solicitacao_servico on(solicitacao.protocolo = solicitacao_servico.solicitacao_protocolo)
inner join servico on(servico.id = solicitacao_servico.servicos_id)

inner join categoriaservico on (servico.categoria_id = categoriaservico.id)

where agenda.data = '2018-05-03' and solicitacao.estado = 0

""",conn)

In [5]:
test

,nome,descricao,horariomarcado,valor,servico_a_prestar
0,mwim-nome,gsfxvlmghfsynhgjeyaq-descricao,03:02:17.308000,770.88,Apicultor
1,mwim-nome,dvhpsxrzwnsmdoqwbrun-descricao,16:58:50.009000,403.09,Pedreiro
2,mwim-nome,zgtafefnghqunfpxayll-descricao,13:32:15.410000,356.92,Ferreiro
3,mwim-nome,qxvtflkoykifovlhseki-descricao,03:15:46.829000,957.71,Medico
4,wxuj-nome,mpiatsdlkikwjoisnclv-descricao,03:43:33.239000,398.08,Designer
5,wxuj-nome,xunzlvujdhciyiomzxnx-descricao,11:20:43.137000,109.66,Nego que passeia com os dog
6,armu-nome,fqputorzjhdsmmwvpcnr-descricao,04:34:12.124000,828.14,Medico
7,lxfp-nome,strzcajnugntpjsttgyd-descricao,10:39:30.703000,258.43,Empregado
8,lxfp-nome,eclwodcqzywpefxfzmol-descricao,21:36:28.742000,609.32,Empregado
9,kovm-nome,daybrwmojdkkgwfikzvl-descricao,16:40:15.571000,372.44,Pedreiro
10,kovm-nome,urjdspvmhcbchdyshotz-descricao,22:55:33.791000,237.01,Medico
11,dzcl-nome,avncxqmvlqwabnuyehtm-descricao,09:33:36.150000,812.14,Medico
12,ozrq-nome,owuixtwyxhmvyhmmogct-descricao,04:46:51.185000,1051.86,Medico
13,syqr-nome,bnukabulokqrbjpsnavs-descricao,23:59:30.267000,563.83,Pedreiro
14,syqr-nome,tbqridiytjuicaqiggdb-descricao,18:37:15.820000,160.16,Marceneiro
15,syqr-nome,jceujnfmnagrjcnenhln-descricao,00:27:36.626000,1044.95,Ferreiro
16,syqr-nome,dgedcjlrwkibmupgxswk-descricao,16:48:26.976000,662.82,Designer
17,ecft-nome,wrcfdxiixlubpfpoaqdq-descricao,15:39:02.831000,920.50,Nego que passeia com os dog
18,ecft-nome,aekjemqwncxbwzsxycof-descricao,07:59:13.193000,1000.67,Designer
19,ecft-nome,urovvvpzoqdzxvchwfeh-descricao,10:23:58.044000,422.21,Medico
20,ecft-nome,gqswtgtizofxbjhcktaw-descricao,12:32:59.638000,597.70,Designer
21,ecft-nome,mdpxrothbiscokhzwkwq-descricao,04:35:03.865000,555.21,Pedreiro
22,gztg-nome,rwlwpdvzzxuzzhpzjmmf-descricao,11:37:58.732000,110.66,Pedreiro
23,gztg-nome,grdiovfiiwugaunrwpnv-descricao,01:04:58.901000,761.08,Nego que passeia com os dog
24,gztg-nome,foaybwqhxlkirufwlxyy-descricao,23:51:45.083000,117.47,Empregado
25,rmpt-nome,epwvofariuuhugfetqhl-descricao,22:16:32.450000,456.02,Ferreiro
26,snfk-nome,zfwkimmngilhowigdesa-descricao,23:14:57.289000,531.24,Empregado
27,giit-nome,bqsmpdcqodzfnwtfuvlg-descricao,02:25:13.841000,314.72,Empregado
28,giit-nome,qxrthrjwigtymqefeofc-descricao,22:30:42.854000,297.07,Encanador
29,giit-nome,ovqhoeuzrzfpsnhwdnfp-descricao,11:14:02.220000,620.61,Apicultor
...,...,...,...,...,...
70,uqwv-nome,xzcvcqluvhipfrfwmvlz-descricao,02:54:51.055000,694.15,Empregado
71,uqwv-nome,guygqrhczpupoebwktub-descricao,07:41:38.411000,331.85,Marceneiro
72,uqwv-nome,vnhkopqnkqbcmyrnfdeq-descricao,13:51:34.195000,920.84,Designer
73,uqwv-nome,jrxxwwofxrivzebpdxlb-descricao,12:58:44.671000,171.40,Pintor
74,uqwv-nome,ygatuvhwrjkohfvoqqua-descricao,01:12:16.860000,649.91,Apicultor
75,gavb-nome,oelvozbvhutaqssyltzw-descricao,00:49:11.588000,1049.84,Encanador
76,shjc-nome,oguwptrfrxocpszexodf-descricao,17:10:28.321000,535.80,Designer
77,shjc-nome,lnzqtgcbwpalpdxaimja-descricao,02:26:32.621000,273.40,Nego que passeia com os dog
78,kduc-nome,pmvjhiikhafqqpzgorsa-descricao,19:24:46.629000,519.77,Empregado
79,dcpx-nome,ndmbxdmxlhwtclywbvyq-descricao,08:31:29.601000,248.16,Designer
80,dcpx-nome,njfjnqubdnvzybmqbkas-descricao,05:58:22.321000,866.31,Encanador
81,dcpx-nome,hbedovvizbhfgazqifqy-descricao,05:09:49.094000,648.08,Nego que passeia com os dog
82,dcpx-nome,tqwjyezladtwbfbgorns-descricao,00:09:27.119000,325.02,Ferreiro
83,qwbe-nome,ntaywidrqramhyngupvq-descricao,00:18:15.212000,350.49,Ferreiro
84,qwbe-nome,srpxijniskjmnaluowwr-descricao,19:56:16.308000,387.19,Nego que passeia com os dog
85,hmko-nome,kdenxwxcaopyvbzppdcj-descricao,10:02:36.873000,525.76,Pedreiro
86,alih-nome,iwwezykunvzjcudhnfwb-descricao,13:41:32.375000,303.66,Pedreiro
87,alih-nome,izazubtlwkwewlujlllg-descricao,09:42:41.600000,1023.71,Pedreiro
88,alih-nome,tjvbbfqwaeyzluiywmrq-descricao,22:19:22.995000,590.51,Pedreiro
89,bemm-nome,fniiwnnbddyqwhhsktse-descricao,08:24:36.804000,446.09,Medico
90,bemm-nome,wgspereaxpyrewzmmyie-descricao,00:53:48.882000,1029.71,Empregado
91,ndns-nome,rsqdvlooegblmxdcnwze-descricao,22:42:43.219000,908.10,Medico
92,ndns-nome,yezlfrhjwnggtdghdiha-descricao,17:29:14.551000,469.22,Marceneiro
93,oakb-nome,ywvdvsyoxkcemoyindrp-descricao,12:05:29.519000,452.54,Apicultor
94,snuj-nome,aizwqrvcofmwzmgbiwig-descricao,12:58:14.203000,1023.14,Pintor
95,snuj-nome,pnjgimlnyezmlptkzuay-descricao,21:56:08.723000,1020.65,Encanador
96,snuj-nome,jelgeogxwojbnisiuwbn-descricao,22:43:20.365000,258.75,Encanador
97,pvfw-nome,fatomvihlhajdgyfxsjq-descricao,14:47:37.940000,396.85,Ferreiro
98,pvfw-nome,fzffoagmilxbulvklsko-descricao,11:51:15.251000,497.54,Pintor
99,pvfw-nome,frjlggwmzjcsjfgqdray-descricao,05:18:08.439000,294.55,Medico

# Relatorio2

### Objetivo: Selecionar quais prestadores concluiram um atendimento em uma certa região e o dia

codigo para obtenção do resultado:

In [6]:
result = pd.read_sql_query("""

select prestador.nome as nome_prestador, agenda.data as dia, endereco.CEP from prestador

inner join prestador_agenda on(prestador.id_usuario = prestador_agenda.prestador_id_usuario)
inner join agenda on(agenda.id = prestador_agenda.agenda_id)

inner join agenda_solicitacao on(agenda.id = agenda_solicitacao.agenda_id)
inner join solicitacao on(agenda_solicitacao.solicitacaododia_protocolo = solicitacao.protocolo)

inner join endereco on(endereco.id = solicitacao.endereco_id)

inner join atendimento on(atendimento.prestador_id_usuario = prestador.id_usuario)

where atendimento.concluido = true and endereco.CEP like '2906%'

""",conn)

In [7]:
result

    nome_prestador         dia       cep
0        gvee-nome  2014-12-08  29067654
1        yvob-nome  2016-11-15  29067247
2        yvob-nome  2016-11-15  29067247
3        bkih-nome  2018-07-20  29062918
4        hepl-nome  2012-07-08  29064335
5        size-nome  2013-03-26  29065782
6        qusc-nome  2017-11-27  29066445
7        mnoc-nome  2017-05-03  29060660
8        naml-nome  2012-12-06  29061343
9        tsaq-nome  2015-07-25  29065769
10       tsaq-nome  2015-07-25  29065769
11       qugb-nome  2015-04-12  29060281
12       fxkk-nome  2017-12-27  29067878
13       pgtx-nome  2012-06-29  29066379
14       ttpj-nome  2015-06-18  29068033
15       ljyn-nome  2017-10-23  29069114
16       nvdy-nome  2018-05-22  29068880
17       nvdy-nome  2018-05-22  29068880
18       noaa-nome  2015-05-20  29066367
19       jpwf-nome  2015-04-21  29064849
20       cnzy-nome  2018-04-08  29065910
21       cnzy-nome  2018-04-08  29065910
22       bjia-nome  2014-02-10  29067654
23       xxvm-nome  2018-06-24  29065362
24       xxvm-nome  2018-06-24  29065362
25       ihkr-nome  2014-04-21  29063063
26       yhaj-nome  2017-07-13  29062254
27       rorz-nome  2017-05-24  29063135
28       clfb-nome  2012-11-29  29063220
29       clfb-nome  2012-11-29  29063220
..             ...         ...       ...
630      mrfd-nome  2013-05-18  29060023
631      excz-nome  2013-02-05  29068288
632      ayvs-nome  2012-02-19  29064539
633      yaif-nome  2016-04-23  29065910
634      yaif-nome  2016-04-23  29065910
635      ntfj-nome  2013-09-17  29065474
636      cfog-nome  2014-06-19  29067809
637      rvwd-nome  2018-05-07  29065910
638      rvwd-nome  2018-05-07  29065910
639      vpvp-nome  2018-04-01  29061700
640      flbq-nome  2013-10-25  29065192
641      flbq-nome  2013-10-25  29065192
642      eubc-nome  2012-05-06  29066852
643      xqtd-nome  2012-01-31  29067732
644      rjws-nome  2013-08-01  29069603
645      rjws-nome  2013-08-01  29069603
646      cpbe-nome  2016-08-20  29069682
647      izbu-nome  2018-04-26  29061790
648      izbu-nome  2018-04-26  29061790
649      lyds-nome  2016-10-17  29060167
650      wnzw-nome  2012-08-09  29064293
651      kusd-nome  2013-11-28  29063220
652      ddtu-nome  2016-10-14  29065727
653      cppq-nome  2014-11-27  29067009
654      cppq-nome  2014-11-27  29067009
655      fkwm-nome  2012-05-03  29060281
656      ehdl-nome  2018-11-28  29069132
657      cznk-nome  2012-09-05  29062272
658      zruy-nome  2017-10-23  29063862
659      mzao-nome  2014-06-09  29067591

[660 rows x 3 columns]

References

## Relatório 3

### Objetivo: Selecionar os funcionarios que atenderam e não concluiram o chamado em uma região

codigo para obtenção do resultado:

In [8]:
result = pd.read_sql_query("""

select DISTINCT prestador.nome as nome_prestador, agenda.data as dia_do_ocorrido, categoriaservico.tipo as servico_a_prestar, servico.valor from prestador

inner join prestador_agenda on(prestador.id_usuario = prestador_agenda.prestador_id_usuario)
inner join agenda on(agenda.id = prestador_agenda.agenda_id)

inner join agenda_solicitacao on(agenda.id = agenda_solicitacao.agenda_id)
inner join solicitacao on(agenda_solicitacao.solicitacaododia_protocolo = solicitacao.protocolo)

inner join solicitacao_servico on(solicitacao.protocolo = solicitacao_servico.solicitacao_protocolo)
inner join servico on(servico.id = solicitacao_servico.servicos_id)

inner join categoriaservico on (servico.categoria_id = categoriaservico.id)

inner join atendimento on(atendimento.prestador_id_usuario = prestador.id_usuario)

inner join endereco on(endereco.id = solicitacao.endereco_id)

where solicitacao.estado = 3 and atendimento.concluido = false and endereco.CEP like '2906%'

                            """,conn)

In [9]:
result

    nome_prestador dia_do_ocorrido            servico_a_prestar    valor
0        aicl-nome      2017-12-11                       Medico   385.16
1        aicl-nome      2017-12-11                       Pintor   414.11
2        alyz-nome      2014-06-17                     Ferreiro   800.16
3        alyz-nome      2014-06-17                     Pedreiro   629.48
4        anda-nome      2013-05-06                    Encanador   258.82
5        anda-nome      2013-05-06  Nego que passeia com os dog   861.38
6        arfv-nome      2013-04-08                       Medico   733.45
7        atlk-nome      2017-09-11                    Encanador   752.86
8        bekv-nome      2017-08-06                     Pedreiro   925.08
9        bwqf-nome      2014-06-19                     Ferreiro   577.98
10       bxlu-nome      2012-01-05                     Pedreiro   550.16
11       cgdv-nome      2017-11-15                     Ferreiro   286.32
12       chtp-nome      2015-10-23                    Apicultor   639.11
13       chtp-nome      2015-10-23                   Marceneiro   168.13
14       chtp-nome      2015-10-23                       Medico   577.32
15       cpey-nome      2016-10-26                     Pedreiro   210.24
16       cppq-nome      2014-11-27                    Encanador   141.62
17       cppq-nome      2014-11-27                       Pintor   171.59
18       cvsv-nome      2012-11-30                   Marceneiro   188.79
19       cvsv-nome      2012-11-30                       Medico   245.49
20       cvsv-nome      2012-11-30                     Pedreiro   333.51
21       cvsv-nome      2012-11-30                       Pintor   577.26
22       dbrd-nome      2015-08-14                    Empregado   539.73
23       dbrd-nome      2015-08-14                     Ferreiro   566.30
24       dbrd-nome      2015-08-14                       Medico   256.76
25       ddtu-nome      2016-10-14                     Ferreiro   461.66
26       ddtu-nome      2016-10-14                     Ferreiro   899.45
27       drfd-nome      2016-09-25                   Marceneiro   903.20
28       drfd-nome      2016-09-25                       Pintor   908.14
29       ebqb-nome      2016-05-21                       Medico   911.10
..             ...             ...                          ...      ...
118      whue-nome      2013-10-08                     Pedreiro   809.40
119      woot-nome      2018-03-04                     Designer   674.19
120      woot-nome      2018-03-04                   Marceneiro   295.74
121      wuue-nome      2013-08-10                    Encanador   160.03
122      wuue-nome      2013-08-10                       Medico   577.23
123      xpkw-nome      2012-04-21                     Designer   768.56
124      xpkw-nome      2012-04-21                     Pedreiro   957.86
125      xpkw-nome      2012-04-21                       Pintor  1094.99
126      xums-nome      2015-04-22                    Empregado   829.14
127      xums-nome      2015-04-22                    Encanador   369.50
128      xums-nome      2015-04-22                    Encanador  1024.43
129      xums-nome      2015-04-22  Nego que passeia com os dog   994.58
130      xums-nome      2015-04-22                     Pedreiro   871.55
131      xums-nome      2015-04-22                       Pintor   242.45
132      xums-nome      2015-04-22                       Pintor   704.23
133      ydlm-nome      2014-12-16                    Encanador   696.25
134      ykvy-nome      2016-01-11                    Apicultor   687.31
135      ykvy-nome      2016-01-11                    Apicultor   717.17
136      yrjz-nome      2015-12-22                    Empregado   236.58
137      yrjz-nome      2015-12-22                    Empregado   633.29
138      yrjz-nome      2015-12-22                       Pintor   645.40
139      yygo-nome      2015-04-13                     Designer   239.86
140      yygo-nome      2015-04-13                    Encanador   679.30
141      yykm-nome      2018-08-26                    Apicultor   645.77
142      zlmi-nome      2013-08-04                    Apicultor  1058.88
143      zlmi-nome      2013-08-04  Nego que passeia com os dog  1002.98
144      zlmi-nome      2013-08-04                       Pintor   175.57
145      zqwe-nome      2016-10-31  Nego que passeia com os dog   368.60
146      zwmg-nome      2018-08-21                     Pedreiro   889.30
147      zwtp-nome      2015-10-22                   Marceneiro   360.53

[148 rows x 4 columns]

## Relatório 4

### Objetivo: Visualizar os lucros obtidos das empresas em 2017

codigo para obtenção do resultado:

In [10]:
result = pd.read_sql_query("""

select empresa.nome as nome_empresa, SUM(servico.valor) AS valor_total_ganho  from empresa

inner join empresa_solicitacao on(empresa.id_usuario = empresa_solicitacao.empresa_id_usuario)
inner join solicitacao on(empresa_solicitacao.solicitacaoes_protocolo = solicitacao.protocolo)

inner join solicitacao_servico on(solicitacao.protocolo = solicitacao_servico.solicitacao_protocolo)
inner join servico on(servico.id = solicitacao_servico.servicos_id)

inner join servico_atendimento on(servico.id = servico_atendimento.servico_id)
inner join atendimento on(servico_atendimento.atendimento_id = atendimento.id)

where atendimento.concluido = true and CAST (solicitacao.datasolicitacao as varchar) like '2017%'
group by empresa.nome
                            """,conn)

In [11]:
result

    nome_empresa  valor_total_ganho
0      aaoe-nome             442.32
1      abah-nome             494.49
2      acsx-nome             141.78
3      aczg-nome            1496.74
4      adof-nome            1040.47
5      ahnt-nome             805.46
6      ahtf-nome            1013.41
7      aita-nome             827.01
8      ajdk-nome             745.49
9      ajir-nome             551.21
10     akfm-nome             646.63
11     akhp-nome             674.40
12     alco-nome             324.28
13     ampg-nome             319.86
14     anoc-nome             688.17
15     aoap-nome             596.10
16     apnx-nome             130.76
17     apwi-nome             908.89
18     arak-nome             300.86
19     atde-nome             280.28
20     atwg-nome             450.85
21     atzs-nome             856.49
22     axdr-nome             842.62
23     azws-nome             168.06
24     basl-nome             542.07
25     basp-nome             250.79
26     bbvj-nome             963.05
27     bdaw-nome             413.92
28     bdcd-nome             232.94
29     beoh-nome             698.04
..           ...                ...
649    zcds-nome            1095.80
650    zdex-nome             165.08
651    zdgg-nome             937.46
652    zdqy-nome             460.13
653    zdxy-nome            1069.11
654    zedc-nome             856.79
655    zezl-nome             283.79
656    zilf-nome             473.13
657    zjlu-nome             148.53
658    zlmw-nome            1004.67
659    zlwv-nome            1057.92
660    zmad-nome             554.76
661    zmhj-nome            1085.42
662    zmsq-nome             811.72
663    zmvv-nome             737.18
664    zppn-nome             487.81
665    zrqr-nome             821.09
666    zsic-nome            1044.26
667    ztdo-nome             321.00
668    zumy-nome             843.20
669    zuzn-nome             912.83
670    zwei-nome             803.89
671    zxgc-nome             583.57
672    zxgl-nome             995.18
673    zxlw-nome             506.42
674    zyil-nome             756.69
675    zymz-nome             322.01
676    zzgb-nome             282.65
677    zzpw-nome             331.69
678    zzzo-nome             898.03

[679 rows x 2 columns]

## Relatório 5

### Objetivo:  Selecionar media de multas para clientes

In [16]:
result = pd.read_sql_query("""

select cliente.nome as nome_cliente, SUM(servico.multa) AS multa_total from cliente 

inner join cliente_solicitacao on(cliente.id_usuario = cliente_solicitacao.cliente_id_usuario)
inner join solicitacao on(cliente_solicitacao.solicitacao_protocolo = solicitacao.protocolo)

inner join solicitacao_servico on(solicitacao.protocolo = solicitacao_servico.solicitacao_protocolo)
inner join servico on(servico.id = solicitacao_servico.servicos_id)

group by cliente.nome
having AVG(servico.multa)>0

""",conn)

In [17]:
result

      nome_cliente  multa_total
0        aaan-nome      3055.67
1        aabb-nome      1108.47
2        aabg-nome      4089.46
3        aabh-nome       291.67
4        aabi-nome      1518.22
5        aabo-nome      1818.52
6        aabu-nome      2083.18
7        aace-nome      2201.60
8        aadc-nome       989.60
9        aadg-nome       505.23
10       aadh-nome      2038.25
11       aadr-nome      2045.52
12       aaea-nome      1971.56
13       aaeh-nome      1342.86
14       aaej-nome       435.50
15       aael-nome       961.69
16       aaeo-nome      3288.41
17       aaev-nome      3635.89
18       aaey-nome       258.91
19       aafm-nome      4273.26
20       aaft-nome      4478.48
21       aafv-nome      3985.18
22       aafy-nome       957.97
23       aagg-nome       735.51
24       aaha-nome       123.14
25       aaht-nome      2331.78
26       aaip-nome      1937.92
27       aaiu-nome      2334.84
28       aaiv-nome      2521.76
29       aajh-nome      1507.87
...            ...          ...
51021    zzrf-nome      1993.28
51022    zzri-nome      1397.64
51023    zzrj-nome      1137.16
51024    zzro-nome      1290.34
51025    zzrp-nome       626.34
51026    zzrr-nome       906.03
51027    zzsb-nome      2181.87
51028    zzsj-nome       804.22
51029    zzsq-nome      2073.14
51030    zztb-nome       908.42
51031    zzts-nome      1188.20
51032    zzub-nome      4943.88
51033    zzue-nome       511.10
51034    zzuk-nome       209.20
51035    zzup-nome      4803.43
51036    zzvd-nome      1073.65
51037    zzvf-nome      5463.63
51038    zzvm-nome       986.05
51039    zzvn-nome       379.18
51040    zzvp-nome       398.75
51041    zzwj-nome      2680.58
51042    zzwp-nome      1367.04
51043    zzws-nome      1002.00
51044    zzxa-nome      2607.51
51045    zzxk-nome      1964.98
51046    zzxq-nome      1075.14
51047    zzxu-nome       142.58
51048    zzyh-nome      1140.43
51049    zzyp-nome      1393.94
51050    zzyt-nome      2404.03

[51051 rows x 2 columns]

# Referencias

https://pandas.pydata.org/pandas-docs/stable/style.html <br>
https://pythonspot.com/matplotlib-bar-chart/<br>
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html <br>